default: &default
  adapter: postgresql # ★ 必須
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  # 接続文字列全体ではなく、環境変数名 'DATABASE_URL' のみを指定します
  url: <%= ENV.fetch('DATABASE_URL') %>  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

queue:
  <<: *default
  # 接続文字列全体ではなく、環境変数名 'DATABASE_URL' のみを指定します
  url: <%= ENV.fetch('DATABASE_URL') %> 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>