default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  
production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

queue:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>