default: &default
  adapter: postgresql # RenderはPostgreSQLを使うため、defaultも変更
  encoding: unicode
  # 接続プールの設定。RENDER環境変数を活用
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# 開発環境はローカルで使うPostgreSQLまたは以前のsqlite3に戻します
development:
  <<: *default
  url: <%= ENV['postgresql://mysite_etth_user:MqoNvkAv3o4hgaJijtM8qEXRWuIEWWsB@dpg-d3ecqcmr433s73eh3hvg-a/mysite_etth'] %>

# 本番環境 (Render)
production:
  # Renderの環境変数 'DATABASE_URL' を使ってデータベースに接続する標準的な記述
  url: <%= ENV['postgresql://mysite_etth_user:MqoNvkAv3o4hgaJijtM8qEXRWuIEWWsB@dpg-d3ecqcmr433s73eh3hvg-a/mysite_etth'] %>
  # もしRAILS_MAX_THREADSを使わないなら、poolは直接設定しても良い
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>