# ... (production部分は変更なし)
production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %> # これはあってもOK

queue:
  <<: *default
  # pool設定を削除してシンプルにする
  url: <%= ENV.fetch('DATABASE_URL') %>