default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  # DATABASE_URL 環境変数全体を使用
  url: <%= ENV.fetch('DATABASE_URL') %>
  
queue:
  <<: *default
  # production と同じ接続を使用
  url: <%= ENV.fetch('DATABASE_URL') %>